name: Deploy to Production

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "deploy-production" to confirm'
        required: true
        default: ''

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Validate confirmation (manual trigger only)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirm != 'deploy-production'
        run: |
          echo "❌ Deployment cancelled. Please type 'deploy-production' to confirm."
          exit 1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        env:
          VITE_ENV: production
          VITE_BASE_PATH: /learning-platform/
          VITE_DB_NAME: mindforge-academy
        run: npm run build

      - name: Add 404.html for SPA routing
        run: cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages (root)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: .  # Deploy to root
          keep_files: true    # Keep test directory
          exclude_assets: 'test/**'  # Don't touch test directory
          commit_message: 'Deploy production: ${{ github.event.release.tag_name || github.sha }}'

      - name: Deployment summary
        run: |
          echo "✅ Production deployment successful!"
          echo ""
          echo "🔗 Production URL: https://trsdn.github.io/learning-platform/"
          echo "🔗 Test URL: https://trsdn.github.io/learning-platform/test/ (unchanged)"
          echo ""
          echo "📦 Database: mindforge-academy"
          echo "🏷️  Release: ${{ github.event.release.tag_name || 'Manual deployment' }}"
          echo "🌿 Commit: ${{ github.sha }}"
          echo ""
          echo "⚠️  Note: Clear browser cache (Ctrl+Shift+Delete) before testing!"